### ISSUE TITLE
Dots in linechart after enabling computed-columns

### ISSUE THREAD

**Issue by michimau** [seadiaz/computed-columns#2]
Hi there, 
I like your plugin very much.

However, if I enable it I have a strange side effect on linecharts: blue dots are appearing.
I cannot remove nor can change the color of the dots.
If I remove the plugin, the dots are gone; very curious case.

I use the following steps for including the plugin in my Dockerfile file:
~snip
ADD plugins/computed-columns /kibana/plugins/computed-columns
RUN cd /kibana/plugins/computed-columns && npm install
~snip 
Compilation succeed and I can use the your plugin without any further issue.
This applies to all versions I have tried 5.1.2, 5.2.0, 5.3.2, 5.4.0. 

Any clue?

![bluedots](https://cloud.githubusercontent.com/assets/11296689/26352282/68799932-3fbb-11e7-9d77-162557aa5299.png)

**Comment by michimau** [comment]
seems completely unrelated to the plugin. sorry to bother you.

**Comment by seadiaz** [comment]
No bother at all. I'm happy to hear that people using this plugin.

**Comment by michimau** [comment]
:)

FYI, out of curiosity, the issue came form another plugin, cohort.
Issued a pull request to fix it: https://github.com/elo7/cohort/pull/4

I feel like a more comprehensive guidance on plugins development from the Kibana team should be provided, in order to allow people to write even better software. 

Cheers!!
michimau
