### ISSUE TITLE
Does not work with Kibana 5.4.0

### ISSUE THREAD

**Issue by fbaligand** [seadiaz/computed-columns#4]
I have updated package.json to set 5.4.0 version.
But when I launch the plugin, there is no table displayed, but instead a blank screen.
And I have the following error in browser console :
```
Error: hiddenColumns is undefined
hideColumns@http://myserver:9605/bundles/kibana.bundle.js?v=15063:124:13514
@http://myserver:9605/bundles/kibana.bundle.js?v=15063:124:14809
$delegate.constructor.prototype.$watchMulti/<@http://myserver:9605/bundles/commons.bundle.js?v=15063:82:26925
$digest@http://myserver:9605/bundles/commons.bundle.js?v=15063:39:2869
$apply@http://myserver:9605/bundles/commons.bundle.js?v=15063:39:5026
done@http://myserver:9605/bundles/commons.bundle.js?v=15063:37:25016
completeRequest@http://myserver:9605/bundles/commons.bundle.js?v=15063:37:28702
createHttpBackend/</xhr.onload@http://myserver:9605/bundles/commons.bundle.js?v=15063:37:29634
```

**Comment by seadiaz** [comment]
I fix the issue for Kibana 5.3 and I release version 0.3.1.
Also I upgrade plugin for Kibana 5.4 and I release version 0.4.1

I hope this solve your problem.

😃

**Comment by fbaligand** [comment]
Hi @seadiaz,

First, thanks for your great reactivity !
Then, I tested version 0.4.1 and it works great ! => thanks a lot !

Finally, in your "v0.4.1" release notes, you wrote "Fix hidden columns for Kibana version 4.5".
I guess you mean "Fix hidden columns for Kibana version 5.4.0"

**Comment by seadiaz** [comment]
You have right, my mistake. Plugin version 0.4.1 fix bug for Kibana 5.4.0.

😃

**Comment by fbaligand** [comment]
Sounds better :)

**Comment by vinujamaniccav** [comment]
Hey, I still have the issue. 

>       [ '../plugins/computed-columns-0.4.1/public/computed-columns-vis.js\nModul
e not found: Error: Cannot resolve module \'expr-eval\' in C:\\HOMEWARE\\_ELK\\k
ibana\\plugins\\computed-columns-0.4.1\\public\n @ ../plugins/computed-columns-0
.4.1/public/computed-columns-vis.js 25:16-36',
        '../plugins/computed-columns-0.4.1/public/computed-columns-vis.js\nModul
e not found: Error: Cannot resolve module \'number-to-letter\' in C:\\HOMEWARE\\
_ELK\\kibana\\plugins\\computed-columns-0.4.1\\public\n @ ../plugins/computed-co
lumns-0.4.1/public/computed-columns-vis.js 27:22-49' ],


I am using kibana 5.4 and downloading manually the .zip and integrating  in 
kibana\plugins

**Comment by seadiaz** [comment]
Did you run npm install? expr-eval is a plugin dependency.

Why did you install manually? It is easier to use kibana-plugin script.

--
Sebastián Díaz

**Comment by vinujamaniccav** [comment]
Hey, 

Because I have proxy restriction to use npm and download and install automatically.
To do see any solution ?

Regards
Vinuja

**Comment by fbaligand** [comment]
Yes.
First , download last release : https://github.com/seadiaz/computed-columns/releases/download/0.5.0/computed-columns-0.5.0-5.4.0.zip

Then launch plugin install using Kibana CLI : 
/kibana/bin/kibana-plugin install file:///path/to/archive.zip

**Comment by vinujamaniccav** [comment]
Hey, 

First of all, thank you for your help.
But I have already tried it and I have the following  message: 

> Plugin installation was unsuccessful due to error " No kibana plugins found in archive" 


In the package,json the kibana version matches with the one launched.

**Comment by fbaligand** [comment]
ah... this is weird.
I just tested to install this archive in Kibana 5.4.0, and it works fine.
I invite you to check the zip content (with unzip command for instance).

Else, you can install it manually :
```
cd /kibana/plugins
unzip /path/to/computed-columns-0.5.0-5.4.0.zip
mv kibana/computed-columns .
rm -rf kibana
rm -rf ../optimize
```
at first kibana startup, it will "compile" all javascript to "optimize" folder. It takes some minutes.
Next startups will be fast.

**Comment by vinujamaniccav** [comment]
I have the following message when I do  `mv kibana/computed-columns `. : 

> mv: cannot stat `kibana/computed-columns': No such file or directory

Its maybe because I have dowloaded the code source? 
When I am trying to download  computed-columns-0.5.0-5.4.0.zip  it is said : might be temporarily down or it may have moved permanently to a new web address.

**Comment by fbaligand** [comment]
The zip contains a "kibana" root folder, which contains a "computer-columns" folder.
So it seems that your main problem is to manage to download correctly this zip file.
Once done, Kibana CLI should work fine.
