### ISSUE TITLE
Bug : incompatible with "Split Table" mode

### ISSUE THREAD

**Issue by fbaligand** [seadiaz/computed-columns#5]
When I add an aggregation bucket, if I choose "Split Table" option, then the resulting visualization is a "blank screen" :
![image](https://cloud.githubusercontent.com/assets/3750300/26828101/3a9632e0-4ac0-11e7-9250-717662734cb8.png)

In my browser console, I get the following error :
```
Error: table.columns is undefined
@http://localhost:9605/bundles/kibana.bundle.js?v=15063:131:14711
arrayEach@http://localhost:9605/bundles/commons.bundle.js?v=15063:1:10718
runInContext/createForEach/<@http://localhost:9605/bundles/commons.bundle.js?v=15063:2:2520
@http://localhost:9605/bundles/kibana.bundle.js?v=15063:131:14599
arrayEach@http://localhost:9605/bundles/commons.bundle.js?v=15063:1:10718
runInContext/createForEach/<@http://localhost:9605/bundles/commons.bundle.js?v=15063:2:2520
@http://localhost:9605/bundles/kibana.bundle.js?v=15063:131:14524
$delegate.constructor.prototype.$watchMulti/<@http://localhost:9605/bundles/commons.bundle.js?v=15063:82:26925
$digest@http://localhost:9605/bundles/commons.bundle.js?v=15063:39:2869
$apply@http://localhost:9605/bundles/commons.bundle.js?v=15063:39:5026
done@http://localhost:9605/bundles/commons.bundle.js?v=15063:37:25016
completeRequest@http://localhost:9605/bundles/commons.bundle.js?v=15063:37:28702
createHttpBackend/</xhr.onload@http://localhost:9605/bundles/commons.bundle.js?v=15063:37:29634
```

Kibana version : 5.4.0
Computed Columns version : v0.4.1

**Comment by seadiaz** [comment]
Fabián, I never try that options. Let me reproduce my self the error and fix it ASAP.

--
Sebastián Díaz

**Comment by fbaligand** [comment]
@seadiaz 
Thanks a lot to look at this !

**Comment by vinujamaniccav** [comment]
Hey, I have the same issue. Is there are solution founded  for this issue?

**Comment by fbaligand** [comment]
No solution found for this issue. 
I wait for the fix.

**Comment by seadiaz** [comment]
Bug fixed in release 0.6.0.

**Comment by fbaligand** [comment]
Thanks a lot @seadiaz !
I will try to test it today.

**Comment by fbaligand** [comment]
Hi, 

I just try it and it works great ! => Thanks a lot !

However, it seems it requires to create a fresh new datatable : I don't manage to add a "split table" bucket on my previously existing "computed columns" datatable.

**Comment by vinujamaniccav** [comment]
Hey, I am using kibana 5.4.0, how do I do to benefit of the debug?

**Comment by fbaligand** [comment]
- download : https://github.com/seadiaz/computed-columns/releases/download/0.6.0/computed-columns-0.6.0-5.4.3.zip
- unzip it, in file kibana/computed-columns/package.json, replace `"5.4.3"` by `"5.4.0"`
- zip it and deploy it using `/opt/kibana/bin/kibana-plugin install file:///path/to/computed-columns.zip`

**Comment by vinujamaniccav** [comment]
Hi, 

Thanks a lot, I have installed the release. Therefore, the hidden columns seems to not work with the slit table. I have a blank screen as soon as I put something in the hidden columns field.

**Comment by fbaligand** [comment]
You're right, I reproduce your issue.
As this issue is closed and released, I invite you to open a new issue to explain problem.
Please provide your browser console logs.

**Comment by vinujamaniccav** [comment]
Thanks fBaligand for your advise. I did it.
