### ISSUE TITLE
Enhancement : set "Data" as visualization type

### ISSUE THREAD

**Issue by fbaligand** [seadiaz/computed-columns#6]
Today, standard "Data Table" visualization has "Data" as visualization type.
But "Computed Columns" visualization has "Other" as visualization type.
It would be nice to set same visualization type than standard "Data Table".

![image](https://cloud.githubusercontent.com/assets/3750300/26836198/8291c414-4ada-11e7-9fbc-fa43fa731904.png)

**Comment by seadiaz** [comment]
That group is new in Kibana 5.4 and I don't know if plugins have access to define where to be put in. I will investigate what I can do.

--
Sebastián Díaz

**Comment by fbaligand** [comment]
Hi @seadiaz ,

It seems that to do that, you have to add the following config line :
https://github.com/elastic/kibana/blob/master/src/core_plugins/table_vis/public/table_vis.js#L39

**Comment by seadiaz** [comment]
Great!

Could you please send me a PR?

--
Sebastián Díaz

**Comment by fbaligand** [comment]
Done !

**Comment by seadiaz** [comment]
Thanks @fbaligand for your contribution.

In a moment I will release a new version.

**Comment by seadiaz** [comment]
Sorry about my inactivity time.

New release 0.6.0 includes your contribution.

Thanks again!

**Comment by fbaligand** [comment]
No problem ! Thanks for the release !
