### ISSUE TITLE
col[4] is always equal to 2.718

### ISSUE THREAD

**Issue by mpaduada** [seadiaz/computed-columns#8]
If there are at least five columns, then `col[4]` (corresponding to the 5th column) is always equal to 2.718.

For example, see this screen shot for a trivial example in which the first column is a simple count metric, and each of the next four calculated columns has a formula that points to the immediately preceding column.

![screen shot 2017-06-08 at 11 49 06](https://user-images.githubusercontent.com/448739/26937920-bfa6ef16-4c40-11e7-898a-856518a5a1d0.png)

I've reproduced this result both when the 5th column is populated by a metric in the Data tab and when it's populated by a computed column in the Options tab.

My temporary workaround is to treat the 5th column as a dummy column and add it to the hidden columns list.

**Comment by seadiaz** [comment]
I think you are using an old version. Release 0.5.0 fix that issue.

Please try it and let me know if bug pesists.

--
Sebastián Díaz

**Comment by mpaduada** [comment]
Yes, you're right. Release 0.5.0 works nicely. Thanks!
